index script

diff --git a/p5-search-engine/bin/index b/p5-search-engine/bin/index
--- a/p5-search-engine/bin/index
+++ b/p5-search-engine/bin/index
@@ -20,28 +20,43 @@ fi
 # Parse argument.  $1 is the first argument
 case $1 in
   "start")
+    if pgrep -f "flask --app index run --host 0.0.0.0 --port 9000" > /dev/null
+    then
+        echo "Error: index server is already running"
+        exit 1
+    fi
+    if pgrep -f "flask --app index run --host 0.0.0.0 --port 9001" > /dev/null
+    then
+        echo "Error: index server is already running"
+        exit 1
+    fi
+    if pgrep -f "flask --app index run --host 0.0.0.0 --port 9002" > /dev/null
+    then
+        echo "Error: index server is already running"
+        exit 1
+    fi
     echo "starting index server ..."
     mkdir -p var/log
     rm -f var/log/index.log
-    INDEX_PATH="inverted_index_0.txt" flask --app index run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1
-    INDEX_PATH="inverted_index_1.txt" flask --app index run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1
-    INDEX_PATH="inverted_index_2.txt" flask --app index run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1
+    INDEX_PATH="inverted_index_0.txt" flask --app index run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
+    INDEX_PATH="inverted_index_1.txt" flask --app index run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
+    INDEX_PATH="inverted_index_2.txt" flask --app index run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
     ;;
 
 
   "stop")
     echo "stopping index server ..."
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9000"
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9001"
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9002"
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9000" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9001" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9002" || true
     ;;
 
 
   "restart")
     echo "stopping index server ..."
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9000"
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9001"
-    pkill -f "flask --app index run --host 0.0.0.0 --port 9002"
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9000" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9001" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9002" || true
     echo "starting index server ..."
     mkdir -p var/log
     rm -f var/log/index.log
